# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caloriewatcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise',
            field=models.IntegerField(verbose_name='exercise'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='minute',
            field=models.IntegerField(verbose_name='minute'),
        ),
        migrations.AlterField(
            model_name='food',
            name='date_consumed',
            field=models.DateField(auto_now_add=True, verbose_name='date consumed'),
        ),
    ]
