# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caloriewatcher', '0004_auto_20161215_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='when',
        ),
        migrations.RemoveField(
            model_name='food',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='food',
            name='when',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='label',
            field=models.CharField(max_length=100, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='quantity',
            field=models.FloatField(verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='unit'),
        ),
    ]
