# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caloriewatcher', '0005_auto_20161215_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrient',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='measure',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='what',
        ),
        migrations.RemoveField(
            model_name='food',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='food',
            name='measure',
        ),
        migrations.RemoveField(
            model_name='food',
            name='what',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Nutrient',
        ),
    ]
