# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 18:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(verbose_name='user height in cm')),
                ('weight', models.FloatField(verbose_name='user weight in kg')),
                ('born', models.DateTimeField(verbose_name='mm/yyyy')),
                ('gender', models.CharField(max_length=1, verbose_name='user gender in 1 letter')),
                ('bmi', models.FloatField(blank=True, null=True, verbose_name='BMI')),
                ('bmr', models.FloatField(blank=True, null=True, verbose_name='BMR')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
