# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20161207_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='born',
            field=models.DateTimeField(null=True, verbose_name='mm/yyyy'),
        ),
    ]
