# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20161214_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bmi',
            field=models.FloatField(blank=True, null=True, verbose_name='BMI'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bmr',
            field=models.FloatField(blank=True, null=True, verbose_name='BMR'),
        ),
    ]
