# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20161214_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='born',
            new_name='date_of_birth',
        ),
    ]
